class CreatePosts < ActiveRecord::Migration[5.1]
  def change
    create_table :posts do |t|
    	t.string :title
    	t.string :author
    	t.string :content

    	t.boolean :dungeons_and_dragons

    	t.string :character_name
    	t.string :character_player
    	t.string :character_class
    	t.integer :character_level
    	t.string :character_race
    	t.string :character_alignment
    	t.string :character_deity
    	t.string :character_size
    	t.integer :character_age
    	t.string :character_gender
    	t.string :character_height
    	t.string :character_weight
    	t.string :character_eyes
    	t.string :character_hair
    	t.string :character_skin

    	t.integer :character_attr_str_base
    	t.integer :character_attr_str_mod
    	t.integer :character_attr_str_tempbase
    	t.integer :character_attr_str_tempmod
    	t.integer :character_attr_dex_base
    	t.integer :character_attr_dex_mod
    	t.integer :character_attr_dex_tempbase
    	t.integer :character_attr_dex_tempmod
    	t.integer :character_attr_con_base
    	t.integer :character_attr_con_mod
    	t.integer :character_attr_con_tempbase
    	t.integer :character_attr_con_tempmod
    	t.integer :character_attr_int_base
    	t.integer :character_attr_int_mod
    	t.integer :character_attr_int_tempbase
    	t.integer :character_attr_int_tempmod
    	t.integer :character_attr_wis_base
    	t.integer :character_attr_wis_mod
    	t.integer :character_attr_wis_tempbase
    	t.integer :character_attr_wis_tempmod
    	t.integer :character_attr_cha_base
    	t.integer :character_attr_cha_mod
    	t.integer :character_attr_cha_tempbase
    	t.integer :character_attr_cha_tempmod

    	t.integer :character_hp_max
    	t.integer :character_hp_current
    	t.integer :character_hp_nonlethaldamage
    	t.integer :character_speed
    	t.integer :character_ac_total
    	t.integer :character_ac_armorbonus
    	t.integer :character_ac_shieldbonus
    	t.integer :character_ac_dexmod
    	t.integer :character_ac_natarmor
    	t.integer :character_ac_deflectmod
    	t.integer :character_ac_miscmod
    	t.integer :character_damagereduction
    	t.integer :character_touch
    	t.integer :character_flatfooted
    	t.integer :character_initiative_total
    	t.integer :character_initiative_dexmod
    	t.integer :character_initiative_miscmod

    	t.integer :character_fortitude_total
    	t.integer :character_fortitude_base
    	t.integer :character_fortitude_abilitymod
    	t.integer :character_fortitude_magicmod
    	t.integer :character_fortitude_miscmod
    	t.integer :character_fortitude_tempmod
    	t.integer :character_reflex_total
    	t.integer :character_reflex_base
    	t.integer :character_reflex_abilitymod
    	t.integer :character_reflex_magicmod
    	t.integer :character_reflex_miscmod
    	t.integer :character_reflex_tempmod
    	t.integer :character_will_total
    	t.integer :character_will_base
    	t.integer :character_will_abilitymod
    	t.integer :character_will_magicmod
    	t.integer :character_will_miscmod
    	t.integer :character_will_tempmod
    	t.string :character_conditionalmod

    	t.integer :character_bab
    	t.integer :character_spellresistance
    	t.integer :character_grapple_total
    	t.integer :character_grapple_bab
    	t.integer :character_grapple_strmod
    	t.integer :character_grapple_sizemod
    	t.integer :character_grapple_miscmod

    	t.string :character_attackone_name
    	t.integer :character_attackone_bonus
    	t.integer :character_attackone_damage
    	t.integer :character_attackone_critical
    	t.string :character_attackone_range
    	t.string :character_attackone_type
    	t.string :character_attackone_note
    	t.string :character_attackone_ammoname
    	t.integer :character_attackone_ammocounter

    	t.string :character_attacktwo_name
    	t.integer :character_attacktwo_bonus
    	t.integer :character_attacktwo_damage
    	t.integer :character_attacktwo_critical
    	t.string :character_attacktwo_range
    	t.string :character_attacktwo_type
    	t.string :character_attacktwo_note
    	t.string :character_attacktwo_ammoname
    	t.integer :character_attacktwo_ammocounter

    	t.string :character_attackthree_name
    	t.integer :character_attackthree_bonus
    	t.integer :character_attackthree_damage
    	t.integer :character_attackthree_critical
    	t.string :character_attackthree_range
    	t.string :character_attackthree_type
    	t.string :character_attackthree_note
    	t.string :character_attackthree_ammoname
    	t.integer :character_attackthree_ammocounter

    	t.string :character_attackfour_name
    	t.integer :character_attackfour_bonus
    	t.integer :character_attackfour_damage
    	t.integer :character_attackfour_critical
    	t.string :character_attackfour_range
    	t.string :character_attackfour_type
    	t.string :character_attackfour_note
    	t.string :character_attackfour_ammoname
    	t.integer :character_attackfour_ammocounter

    	t.string :character_attackfive_name
    	t.integer :character_attackfive_bonus
    	t.integer :character_attackfive_damage
    	t.integer :character_attackfive_critical
    	t.string :character_attackfive_range
    	t.string :character_attackfive_type
    	t.string :character_attackfive_note
    	t.string :character_attackfive_ammoname
    	t.integer :character_attackfive_ammocounter

    	t.integer :character_skill_maxclassranks
    	t.integer :character_skill_maxcrossclassranks

    	t.boolean :character_skill_appraise_usable
    	t.integer :character_skill_appraise_skillmod
    	t.integer :character_skill_appraise_abilitymod
    	t.integer :character_skill_appraise_rank
    	t.integer :character_skill_appraise_miscmod
    	t.boolean :character_skill_balance_usable
    	t.integer :character_skill_balance_skillmod
    	t.integer :character_skill_balance_abilitymod
    	t.integer :character_skill_balance_rank
    	t.integer :character_skill_balance_miscmod
    	t.boolean :character_skill_bluff_usable
    	t.integer :character_skill_bluff_skillmod
    	t.integer :character_skill_bluff_abilitymod
    	t.integer :character_skill_bluff_rank
    	t.integer :character_skill_bluff_miscmod
    	t.boolean :character_skill_climb_usable
    	t.integer :character_skill_climb_skillmod
    	t.integer :character_skill_climb_abilitymod
    	t.integer :character_skill_climb_rank
    	t.integer :character_skill_climb_miscmod
    	t.boolean :character_skill_concentration_usable
    	t.integer :character_skill_concentration_skillmod
    	t.integer :character_skill_concentration_abilitymod
    	t.integer :character_skill_concentration_rank
    	t.integer :character_skill_concentration_miscmod
    	t.boolean :character_skill_craftone_usable
    	t.string :character_skill_craftone_name
    	t.integer :character_skill_craftone_skillmod
    	t.integer :character_skill_craftone_abilitymod
    	t.integer :character_skill_craftone_rank
    	t.integer :character_skill_craftone_miscmod
    	t.boolean :character_skill_crafttwo_usable
    	t.string :character_skill_crafttwo_name
    	t.integer :character_skill_crafttwo_skillmod
    	t.integer :character_skill_crafttwo_abilitymod
    	t.integer :character_skill_crafttwo_rank
    	t.integer :character_skill_crafttwo_miscmod
    	t.boolean :character_skill_craftthree_usable
    	t.string :character_skill_craftthree_name
    	t.integer :character_skill_craftthree_skillmod
    	t.integer :character_skill_craftthree_abilitymod
    	t.integer :character_skill_craftthree_rank
    	t.integer :character_skill_craftthree_miscmod
    	t.boolean :character_skill_decipherscript_usable
    	t.integer :character_skill_decipherscript_skillmod
    	t.integer :character_skill_decipherscript_abilitymod
    	t.integer :character_skill_decipherscript_rank
    	t.integer :character_skill_decipherscript_miscmod
    	t.boolean :character_skill_diplomacy_usable
    	t.integer :character_skill_diplomacy_skillmod
    	t.integer :character_skill_diplomacy_abilitymod
    	t.integer :character_skill_diplomacy_rank
    	t.integer :character_skill_diplomacy_miscmod
    	t.boolean :character_skill_disabledevice_usable
    	t.integer :character_skill_disabledevice_skillmod
    	t.integer :character_skill_disabledevice_abilitymod
    	t.integer :character_skill_disabledevice_rank
    	t.integer :character_skill_disabledevice_miscmod
    	t.boolean :character_skill_disguise_usable
    	t.integer :character_skill_disguise_skillmod
    	t.integer :character_skill_disguise_abilitymod
    	t.integer :character_skill_disguise_rank
    	t.integer :character_skill_disguise_miscmod
    	t.boolean :character_skill_escapeartist_usable
    	t.integer :character_skill_escapeartist_skillmod
    	t.integer :character_skill_escapeartist_abilitymod
    	t.integer :character_skill_escapeartist_rank
    	t.integer :character_skill_escapeartist_miscmod
    	t.boolean :character_skill_forgery_usable
    	t.integer :character_skill_forgery_skillmod
    	t.integer :character_skill_forgery_abilitymod
    	t.integer :character_skill_forgery_rank
    	t.integer :character_skill_forgery_miscmod
    	t.boolean :character_skill_gatherinfo_usable
    	t.integer :character_skill_gatherinfo_skillmod
    	t.integer :character_skill_gatherinfo_abilitymod
    	t.integer :character_skill_gatherinfo_rank
    	t.integer :character_skill_gatherinfo_miscmod
    	t.boolean :character_skill_handleanimal_usable
    	t.integer :character_skill_handleanimal_skillmod
    	t.integer :character_skill_handleanimal_abilitymod
    	t.integer :character_skill_handleanimal_rank
    	t.integer :character_skill_handleanimal_miscmod
    	t.boolean :character_skill_heal_usable
    	t.integer :character_skill_heal_skillmod
    	t.integer :character_skill_heal_abilitymod
    	t.integer :character_skill_heal_rank
    	t.integer :character_skill_heal_miscmod
    	t.boolean :character_skill_hide_usable
    	t.integer :character_skill_hide_skillmod
    	t.integer :character_skill_hide_abilitymod
    	t.integer :character_skill_hide_rank
    	t.integer :character_skill_hide_miscmod
    	t.boolean :character_skill_intimidate_usable
    	t.integer :character_skill_intimidate_skillmod
    	t.integer :character_skill_intimidate_abilitymod
    	t.integer :character_skill_intimidate_rank
    	t.integer :character_skill_intimidate_miscmod
    	t.boolean :character_skill_jump_usable
    	t.integer :character_skill_jump_skillmod
    	t.integer :character_skill_jump_abilitymod
    	t.integer :character_skill_jump_rank
    	t.integer :character_skill_jump_miscmod
    	t.boolean :character_skill_knowledgeone_usable
    	t.string :character_skill_knowledgeone_name
    	t.integer :character_skill_knowledgeone_skillmod
    	t.integer :character_skill_knowledgeone_abilitymod
    	t.integer :character_skill_knowledgeone_rank
    	t.integer :character_skill_knowledgeone_miscmod
    	t.boolean :character_skill_knowledgetwo_usable
    	t.string :character_skill_knowledgetwo_name
    	t.integer :character_skill_knowledgetwo_skillmod
    	t.integer :character_skill_knowledgetwo_abilitymod
    	t.integer :character_skill_knowledgetwo_rank
    	t.integer :character_skill_knowledgetwo_miscmod
    	t.boolean :character_skill_knowledgethree_usable
    	t.string :character_skill_knowledgethree_name
    	t.integer :character_skill_knowledgethree_skillmod
    	t.integer :character_skill_knowledgethree_abilitymod
    	t.integer :character_skill_knowledgethree_rank
    	t.integer :character_skill_knowledgethree_miscmod
    	t.boolean :character_skill_knowledgefour_usable
    	t.string :character_skill_knowledgefour_name
    	t.integer :character_skill_knowledgefour_skillmod
    	t.integer :character_skill_knowledgefour_abilitymod
    	t.integer :character_skill_knowledgefour_rank
    	t.integer :character_skill_knowledgefour_miscmod
    	t.boolean :character_skill_knowledgefive_usable
    	t.string :character_skill_knowledgefive_name
    	t.integer :character_skill_knowledgefive_skillmod
    	t.integer :character_skill_knowledgefive_abilitymod
    	t.integer :character_skill_knowledgefive_rank
    	t.integer :character_skill_knowledgefive_miscmod
    	t.boolean :character_skill_listen_usable
    	t.integer :character_skill_listen_skillmod
    	t.integer :character_skill_listen_abilitymod
    	t.integer :character_skill_listen_rank
    	t.integer :character_skill_listen_miscmod
    	t.boolean :character_skill_movesilent_usable
    	t.integer :character_skill_movesilent_skillmod
    	t.integer :character_skill_movesilent_abilitymod
    	t.integer :character_skill_movesilent_rank
    	t.integer :character_skill_movesilent_miscmod
    	t.boolean :character_skill_openlock_usable
    	t.integer :character_skill_openlock_skillmod
    	t.integer :character_skill_openlock_abilitymod
    	t.integer :character_skill_openlock_rank
    	t.integer :character_skill_openlock_miscmod
    	t.boolean :character_skill_performone_usable
    	t.string :character_skill_performone_name
    	t.integer :character_skill_performone_skillmod
    	t.integer :character_skill_performone_abilitymod
    	t.integer :character_skill_performone_rank
    	t.integer :character_skill_performone_miscmod
    	t.boolean :character_skill_performtwo_usable
    	t.string :character_skill_performtwo_name
    	t.integer :character_skill_performtwo_skillmod
    	t.integer :character_skill_performtwo_abilitymod
    	t.integer :character_skill_performtwo_rank
    	t.integer :character_skill_performtwo_miscmod
    	t.boolean :character_skill_performthree_usable
    	t.string :character_skill_performthree_name
    	t.integer :character_skill_performthree_skillmod
    	t.integer :character_skill_performthree_abilitymod
    	t.integer :character_skill_performthree_rank
    	t.integer :character_skill_performthree_miscmod
    	t.boolean :character_skill_professionone_usable
    	t.string :character_skill_professionone_name
    	t.integer :character_skill_professionone_skillmod
    	t.integer :character_skill_professionone_abilitymod
    	t.integer :character_skill_professionone_rank
    	t.integer :character_skill_professionone_miscmod
    	t.boolean :character_skill_professiontwo_usable
    	t.string :character_skill_professiontwo_name
    	t.integer :character_skill_professiontwo_skillmod
    	t.integer :character_skill_professiontwo_abilitymod
    	t.integer :character_skill_professiontwo_rank
    	t.integer :character_skill_professiontwo_miscmod
    	t.boolean :character_skill_ride_usable
    	t.integer :character_skill_ride_skillmod
    	t.integer :character_skill_ride_abilitymod
    	t.integer :character_skill_ride_rank
    	t.integer :character_skill_ride_miscmod
    	t.boolean :character_skill_search_usable
    	t.integer :character_skill_search_skillmod
    	t.integer :character_skill_search_abilitymod
    	t.integer :character_skill_search_rank
    	t.integer :character_skill_search_miscmod
    	t.boolean :character_skill_sensemotive_usable
    	t.integer :character_skill_sensemotive_skillmod
    	t.integer :character_skill_sensemotive_abilitymod
    	t.integer :character_skill_sensemotive_rank
    	t.integer :character_skill_sensemotive_miscmod
    	t.boolean :character_skill_sleightofhand_usable
    	t.integer :character_skill_sleightofhand_skillmod
    	t.integer :character_skill_sleightofhand_abilitymod
    	t.integer :character_skill_sleightofhand_rank
    	t.integer :character_skill_sleightofhand_miscmod
    	t.boolean :character_skill_spellcraft_usable
    	t.integer :character_skill_spellcraft_skillmod
    	t.integer :character_skill_spellcraft_abilitymod
    	t.integer :character_skill_spellcraft_rank
    	t.integer :character_skill_spellcraft_miscmod
    	t.boolean :character_skill_spot_usable
    	t.integer :character_skill_spot_skillmod
    	t.integer :character_skill_spot_abilitymod
    	t.integer :character_skill_spot_rank
    	t.integer :character_skill_spot_miscmod
    	t.boolean :character_skill_survival_usable
    	t.integer :character_skill_survival_skillmod
    	t.integer :character_skill_survival_abilitymod
    	t.integer :character_skill_survival_rank
    	t.integer :character_skill_survival_miscmod
    	t.boolean :character_skill_swim_usable
    	t.integer :character_skill_swim_skillmod
    	t.integer :character_skill_swim_abilitymod
    	t.integer :character_skill_swim_rank
    	t.integer :character_skill_swim_miscmod
    	t.boolean :character_skill_tumble_usable
    	t.integer :character_skill_tumble_skillmod
    	t.integer :character_skill_tumble_abilitymod
    	t.integer :character_skill_tumble_rank
    	t.integer :character_skill_tumble_miscmod
    	t.boolean :character_skill_usemagicdevice_usable
    	t.integer :character_skill_usemagicdevice_skillmod
    	t.integer :character_skill_usemagicdevice_abilitymod
    	t.integer :character_skill_usemagicdevice_rank
    	t.integer :character_skill_usemagicdevice_miscmod
    	t.boolean :character_skill_userope_usable
    	t.integer :character_skill_userope_skillmod
    	t.integer :character_skill_userope_abilitymod
    	t.integer :character_skill_userope_rank
    	t.integer :character_skill_userope_miscmod

    	t.boolean :character_skill_extraskillone_usable
    	t.string :character_skill_extraskillone_name
    	t.string :character_skill_extraskillone_keyability
    	t.integer :character_skill_extraskillone_skillmod
    	t.integer :character_skill_extraskillone_abilitymod
    	t.integer :character_skill_extraskillone_rank
    	t.integer :character_skill_extraskillone_miscmod
    	t.boolean :character_skill_extraskilltwo_usable
    	t.string :character_skill_extraskilltwo_name
    	t.string :character_skill_extraskilltwo_keyability
    	t.integer :character_skill_extraskilltwo_skillmod
    	t.integer :character_skill_extraskilltwo_abilitymod
    	t.integer :character_skill_extraskilltwo_rank
    	t.integer :character_skill_extraskilltwo_miscmod
    	t.boolean :character_skill_extraskillthree_usable
    	t.string :character_skill_extraskillthree_name
    	t.string :character_skill_extraskillthree_keyability
    	t.integer :character_skill_extraskillthree_skillmod
    	t.integer :character_skill_extraskillthree_abilitymod
    	t.integer :character_skill_extraskillthree_rank
    	t.integer :character_skill_extraskillthree_miscmod

    	t.timestamps
    end
  end
end
